export const DOUGH_CHEF_PROCESSING_TIME_IN_SECONDS = 7;
export const TOPPING_CHEF_PROCESSING_TIME_IN_SECONDS = 4;
export const OVEN_PROCESSING_TIME_IN_SECONDS = 10;
export const SERVING_PROCESSING_TIME_IN_SECONDS = 5;
