version: '3.9'
services:
  #  backend:
  #    container_name: prm_backend
  #    restart: always
  #    build: .
  #    environment:
  #      - APP_ENV=development
  #      - APP_PORT=9000
  #    volumes:
  #      - ./src:/var/www/prm/src
  #      - ./test:/var/www/prm/test
  #    working_dir: /var/www/prm
  #    ports:
  #      - "3000:3000"
  #    links:
  #      - mysql
  #    depends_on:
  #      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prm
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    #    volumes:
    #      - ./scripts/mysql/init.sql:/var/lib/mysql/init.sql
volumes:
  prm_mysql_data:
#networks:
#  default:
#    external:
#      name: prm
