version: '3.9'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prm
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - "./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
